---

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: apache2,apache,php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: copy default html file for site
    tags: apache,apache2,php
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

