- name: install apache2 package
  tags: apache, apache2
  apt:
   name:
     - apache2
     - libapache2-mod-php

- name: copy html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
